import './globals.css'
import Nav from '../components/navigation/Nav'
import UrlBar from '../lib/UrlBar/UrlBar'


interface MetaData {title: string, description: string}

export const metadata: MetaData = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

function RootLayout(
  { children }: { children: React.ReactNode }
){
  return (
    <html lang="en" className='bg-slate-200 p-4'>
      <body className='bg-slate-700 p-4 rounded-lg'>
        <Nav/>
        {children}
        <UrlBar/>
      </body>
    </html>
  )
}

export default RootLayout