import './globals.css'

interface MetaData {title: string, description: string}

export const metadata: MetaData = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

function RootLayout(
  { children }: { children: React.ReactNode }
){
  return (
    <html lang="en">
      <body className=''>{children}</body>
    </html>
  )
}

export default RootLayout