import './globals.css'
import Nav from '../components/navigation/Nav'
import UrlBar from '../lib/UrlBar/UrlBar'

interface MetaData {title: string, description: string}

export const metadata: MetaData = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

function RootLayout(
  { children }: { children: React.ReactNode }
){
  return (
    <html lang="en" className='bg-slate-900 p-4'>
      <body className='my-8 `sm:w-4/5 md:w-1/2 md:mx-auto bg-slate-800 p-4 rounded-lg'>
        <Nav/>
        {children}
        <UrlBar baseURL={`http://localhost:${process.env.PORT}`}/>
      </body>
    </html>
  )
}

export default RootLayout